Resize images during transload
Seiru/ChromeLL-2.0 pull request #1
Opened 2021-04-20 02:18 UTC by ermacaz

Adds configurable options to specify a maximum height or width of an image and resizes it during the transload process.
Currently only for png/jpegs

2021-04-20 02:47 UTC, Seiru requested changes

2021-04-20 02:47 UTC, Seiru commented on src/js/transloader.js
> +					}
Need an else with the callback here, if the png is the correct size already

2021-04-20 02:48 UTC, Seiru commented
This seems to work for resizing pngs, but jpegs don't seem to be resized.

2021-04-20 02:48 UTC, Seiru commented
Here's two I was testing with:

https://upload.wikimedia.org/wikipedia/commons/8/8c/Chess_Large.JPG

https://upload.wikimedia.org/wikipedia/commons/d/d5/Dds40-097_large.jpeg

2021-04-20 15:35 UTC, ermacaz commented
Ok.  Seems I just got lucky with the JPEGS I was testing on.  The two you found have different type of JPEG encoding... Im going to read up a bit and see how to grab the resolution from this format, or rethink how I get the initial resolution in general.    I will push an update once I figure something out.

Thanks for the help

2021-04-21 01:58 UTC, ermacaz commented
OK I added a new commit that simplifies how to get the original resolution regardless of type.  This should fix the jpeg issues and the codepaths that never call the callback

2021-04-26 02:21 UTC, merged